apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-appflowyweb
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowyweb
spec:
  replicas: {{ .Values.appflowyWeb.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: appflowyweb
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: appflowyweb
        {{- include "appflowy-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: appflowyweb
          image: {{ .Values.appflowyWeb.image }}
          ports:
            - containerPort: {{ .Values.appflowyWeb.port }}
              name: appflowyweb
          readinessProbe:
            tcpSocket:
              port: {{ .Values.appflowyWeb.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.appflowyWeb.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.appflowyWeb.resources | nindent 12 }}
