apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "appflowy-cloud.fullname" . }}-ai
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai
spec:
  replicas: {{ .Values.ai.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ai
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        app.kubernetes.io/component: ai
        {{- include "appflowy-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ai
          image: {{ .Values.ai.image }}
          ports:
            - containerPort: {{ .Values.ai.port }}
              name: ai
          env:
            {{- range $key, $value := .Values.ai.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.ai.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.ai.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.ai.resources | nindent 12 }}
