apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-nginx
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nginx
        {{- include "appflowy-cloud.selectorLabels" . | nindent 8 }}
      namespace: {{ .Values.global.namespace }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.ports.http }}
            - name: https
              containerPort: {{ .Values.nginx.ports.https }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- if .Values.nginx.sslSecret.enabled }}
            - name: nginx-ssl
              mountPath: /etc/nginx/ssl
          {{- end }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "appflowy-cloud.fullname" . }}-nginx-config
      {{- if .Values.nginx.sslSecret.enabled }}
        - name: nginx-ssl
          secret:
            secretName: {{ .Values.nginx.sslSecret.name }}
      {{- end }}
