apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "appflowy-cloud.fullname" . }}-gotrue
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotrue
spec:
  replicas: {{ .Values.gotrue.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: gotrue
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        app.kubernetes.io/component: gotrue
        {{- include "appflowy-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gotrue
          image: {{ .Values.gotrue.image }}
          ports:
            - containerPort: {{ .Values.gotrue.port }}
              name: gotrue
          env:
            {{- range $key, $value := .Values.gotrue.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.gotrue.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.gotrue.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {{- toYaml .Values.gotrue.resources | nindent 12 }}
