apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "appflowy-cloud.fullname" . }}-appflowyworker
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowyworker
spec:
  replicas: {{ .Values.appflowyWorker.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: appflowyworker
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        app.kubernetes.io/component: appflowyworker
        {{- include "appflowy-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: appflowyworker
          image: {{ .Values.appflowyWorker.image }}
          env:
            {{- range $key, $value := .Values.appflowyWorker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.appflowyWorker.resources | nindent 12 }}
