apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-minio
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: {{ .Values.minio.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: minio
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio
        {{- include "appflowy-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args:
            - "server"
            - "/data"
            - "--console-address"
            - ":{{ .Values.minio.consolePort }}"
          ports:
            - name: api
              containerPort: {{ .Values.minio.apiPort }}
            - name: console
              containerPort: {{ .Values.minio.consolePort }}
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "{{ .Values.global.appflowyBaseUrl }}/minio"
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.rootPassword | quote }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: {{ .Values.minio.apiPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: {{ .Values.minio.apiPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ include "appflowy-cloud.fullname" . }}-minio
