apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "appflowy-cloud.fullname" . }}-postgres
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  {{- end }}
