apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "appflowy-cloud.fullname" . }}-redis
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      name: redis
  selector:
    app.kubernetes.io/component: redis
    {{- include "appflowy-cloud.selectorLabels" . | nindent 4 }}
