apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-gotrue
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotrue
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gotrue.port }}
      targetPort: gotrue
      name: gotrue
  selector:
    app.kubernetes.io/component: gotrue
    {{- include "appflowy-cloud.selectorLabels" . | nindent 4 }}
