apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-appflowyweb
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowyweb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appflowyWeb.port }}
      targetPort: appflowyweb
      name: appflowyweb
  selector:
    app.kubernetes.io/component: appflowyweb
    {{- include "appflowy-cloud.selectorLabels" . | nindent 4 }}
