apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-appflowycloud
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: appflowycloud
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appflowyCloud.port }}
      targetPort: appflowycloud
      name: appflowycloud
  selector:
    app.kubernetes.io/component: appflowycloud
    {{- include "appflowy-cloud.selectorLabels" . | nindent 4 }}
