apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-nginx
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/component: nginx
    {{- include "appflowy-cloud.selectorLabels" . | nindent 4 }}
