name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'appflowy-cloud/**'
      - '.github/workflows/helm-publish.yml'

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.1

    - name: Lint Helm Chart
      run: helm lint ./appflowy-cloud

    - name: Template Helm Chart (validate)
      run: helm template appflowy-cloud ./appflowy-cloud

    - name: Package Helm Chart
      run: |
        mkdir -p packaged
        helm package ./appflowy-cloud -d packaged/

    - name: Update Helm Repo Index
      run: |
        helm repo index packaged/ --url https://arked-digital.github.io/appflowy-helm

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: packaged
        publish_branch: gh-pages
        force_orphan: true
